In [40]:
from pandas import read_csv
df1=read_csv("./assets/supermarkets.csv")
df1=df1.set_index("ID")
df1.loc[2:4,"City":"Name"]
df1.iloc[1:4,1:5]
df1

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [2]:
df1.loc[:,"State"]=["AR","MO","KA","NY","OH","DC"]
df1

Address           City State Country         Name  Employees
ID                                                                      
1      3666 21st St  San Francisco    AR     USA      Madeira          8
2    735 Dolores St  San Francisco    MO     USA  Bready Shop         15
3       332 Hill St  San Francisco    KA     USA  Super River         25
4      3995 23rd St  San Francisco    NY     USA   Ben's Shop         10
5   1056 Sanchez St  San Francisco    OH     USA      Sanchez         12
6   551 Alvarado St  San Francisco    DC     USA   Richvalley         20

In [9]:
help(geopy)

Help on package geopy:

NAME
    geopy - geopy is a Python 2 and 3 client for several popular geocoding web services.

DESCRIPTION
    geopy makes it easy for Python developers to locate the coordinates of
    addresses, cities, countries, and landmarks across the globe using third-party
    geocoders and other data sources.
    
    geopy is tested against CPython (versions 2.7, 3.4, 3.5, 3.6, 3.7), PyPy, and
    PyPy3. geopy does not and will not support CPython 2.6.

PACKAGE CONTENTS
    compat
    distance
    exc
    extra (package)
    format
    geocoders (package)
    location
    point
    units
    util

VERSION
    1.17.0

FILE
    c:\program files\python36\lib\site-packages\geopy\__init__.py




In [10]:
import geopy
dir(geopy)

['ArcGIS',
 'AzureMaps',
 'Baidu',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'GeocodeFarm',
 'GoogleV3',
 'Here',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'TomTom',
 'What3Words',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'location',
 'point',
 'units',
 'util']

In [65]:
from geopy.geocoders import Nominatim
nom=Nominatim(user_agent='http')
n=nom.geocode('Some Non Existent Address')
print("Non Existent Address returned:", n)
n=nom.geocode('3995 23rd St, San Francisco, CA 94114')
print(n)
print(type(n))
print(n.latitude, " - " , n.longitude, " - ", n.altitude)
from pandas import read_csv
df=read_csv('./assets/supermarkets.csv')
df["Location"]=df["Address"]+","+df["City"]+","+df["State"]
df["Location"]
df["Coordinates"]=df["Location"].apply(nom.geocode)
df

Non Existent Address returned: None
3995, 23rd Street, Noe Valley, SF, California, 94114, USA
<class 'geopy.location.Location'>
37.7529648  -  -122.4317141  -  0.0


ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                    Location  \
0          8         3666 21st St,San Francisco,CA 94114   
1         15       735 Dolores St,San Francisco,CA 94119   
2         25  332 Hill St,San Francisco,California 94114   
3         10         3995 23rd St,San Francisco,CA 94114   
4         12    1056 Sanchez St,San Francisco,California   
5         20      551 Alvarado St,San Francisco,CA 94114   

                                         Coordinates  
0  (3666, 21st Street, Noe Valley, SF, California...  
1                                               None  
2  (332, Hill Street, Noe Valley, SF, California,...  
3  (3995, 23rd Street, Noe Valley, SF, California...  
4  (1056, Sanchez Street, Noe Valley, SF, Califor...  
5  (551, Alvarado Street, Noe Valley, SF, Califor...

In [127]:
import numpy
n=numpy.arange(27)
print(n)
type(n)
print(type(numpy.array([[1,2,3,4,5],[11,12]])))
print(type(numpy.asarray([[1,2,3,4,5],[11,12]])))
n=n.reshape(3,9)
type(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


numpy.ndarray

In [200]:

n = numpy.arange(20)
n = n.reshape(4,5)
print(n)
# Slicing the first two columns across all rows
print(n[:,0:2])

# Slicing a required n x n set
print(n[1:3,3:5])
help(n.flat)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]
[[ 8  9]
 [13 14]]
Help on flatiter object:

class flatiter(builtins.object)
 |  Flat iterator object to iterate over arrays.
 |  
 |  A `flatiter` iterator is returned by ``x.flat`` for any array `x`.
 |  It allows iterating over the array as if it were a 1-D array,
 |  either in a for-loop or by calling its `next` method.
 |  
 |  Iteration is done in row-major, C-style order (the last
 |  index varying the fastest). The iterator can also be indexed using
 |  basic slicing or advanced indexing.
 |  
 |  See Also
 |  --------
 |  ndarray.flat : Return a flat iterator over an array.
 |  ndarray.flatten : Returns a flattened copy of an array.
 |  
 |  Notes
 |  -----
 |  A `flatiter` iterator can not be constructed directly from Python code
 |  by calling the `flatiter` constructor.
 |  
 |  Examples
 |  --------
 |  >>> x = np.arange(6).reshape(2, 3)
 |  >>> fl = x.flat
 |  >>>

In [193]:
l = [ [j*i for j in range(0,4)] for i in range(0,4)]
print(l)

# print(l[:,0:2])
print(len(l))
for i in range(len(l)) :
    print(*[l[i][j] for j in range(1,3)])

[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6], [0, 3, 6, 9]]
4
0 0
1 2
2 4
3 6


In [216]:
l = [ [j*i for j in range(0,3)] for i in range(0,5)]
narr = numpy.array(l)
print(narr)
print(narr.T)

l2 = [[0,1],
      [0,1],
      [0,1],
      [0,1]
     ]
print(l2)
narr = numpy.array(l2)
print(narr)
print(narr.T)

l3 = [[0],
      [0,1],
      [0,1,2]
     ]
print(l3)
narr = numpy.array(l3)
print(narr)
print(narr.T)

[[0 0 0]
 [0 1 2]
 [0 2 4]
 [0 3 6]
 [0 4 8]]
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]
[[0, 1], [0, 1], [0, 1], [0, 1]]
[[0 1]
 [0 1]
 [0 1]
 [0 1]]
[[0 0 0 0]
 [1 1 1 1]]
[[0], [0, 1], [0, 1, 2]]
[list([0]) list([0, 1]) list([0, 1, 2])]
[list([0]) list([0, 1]) list([0, 1, 2])]


In [241]:
import cv2
# All the arguments of hstack and vstack should be of the same dimensions
img = cv2.imread('./assets/sample-color-bar-50x10.png',1)
img_r_attach = numpy.hstack((img, img, img))
cv2.imwrite('./assets/sample-r-stack-out.png',img_r_attach)
img_v_attach = numpy.vstack((img, img, img))
cv2.imwrite('./assets/sample-v-stack-out.png',img_v_attach)
r_list = numpy.hsplit(img_r_attach,50)
v_list = numpy.vsplit(img_v_attach,30)
v_list

[array([[[  0,   0, 255],
         [  0,  26, 255],
         [  0,  26, 255],
         [  0,  26, 255],
         [  0,  51, 255],
         [  0,  51, 255],
         [  0,  51, 255],
         [  0,  77, 255],
         [  0,  77, 255],
         [  0,  77, 255],
         [  0, 102, 255],
         [  0, 102, 255],
         [  0, 102, 255],
         [  0, 128, 255],
         [  0, 128, 255],
         [  0, 128, 255],
         [  0, 153, 255],
         [  0, 153, 255],
         [  0, 153, 255],
         [  0, 179, 255],
         [  0, 179, 255],
         [  0, 179, 255],
         [  0, 204, 255],
         [  0, 204, 255],
         [  0, 204, 255],
         [  0, 230, 255],
         [  0, 230, 255],
         [  0, 230, 255],
         [  0, 255, 255],
         [  0, 255, 255],
         [  0, 255, 255],
         [  0, 255, 230],
         [  0, 255, 230],
         [  0, 255, 230],
         [  0, 255, 204],
         [  0, 255, 204],
         [  0, 255, 179],
         [  0, 255, 179],
         [  